language: node_js
node_js:
  - "stable"
install: npm install
services:
  - MongoDB
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script: npm test
after_success: npm run coverage
